name = "lenz"
main = "worker/index.ts"
compatibility_date = "2024-09-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "lenzz-dbs"
database_id = "111613ff-0ef9-4bae-878d-cb47c8d49a43"
